# Generated by Django 5.1.5 on 2025-02-03 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='grade',
        ),
    ]
